services:
    nginx:
        build:
            context: .
            dockerfile: _docker/nginx/Dockerfile
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost/" ]
            interval: 30s
            timeout: 10s
            retries: 3
        volumes:
            - ./:/var/www/html
        ports:
            - "80:80"
        depends_on:
            php-fpm:
                condition: service_healthy
        container_name: app_server

    php-fpm:
        build:
            context: .
            dockerfile: _docker/php/Dockerfile
        healthcheck:
            test: [ "CMD", "php-fpm", "-t" ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        user: "1000:1000"
        volumes:
            - ./:/var/www/html
        container_name: app_php

    node:
        image: node:22-alpine
        user: "node"
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "5173:5173"
        command: npm run dev -- --host 0.0.0.0
        container_name: tv_workshop_node
