short_open_tag = On
display_errors = On
error_reporting = E_ALL
log_errors = On
error_log = '/var/log/php/error.log'
allow_url_fopen = On
upload_max_filesize = 128M
post_max_size = 128M
max_input_vars = 10000
date.timezone = "Europe/Moscow"
memory_limit = 512M

[mail]
sendmail_path = /usr/bin/mhsendmail --smtp-addr mailhog:1025